### PR TITLE
Updated slides for April 2019

### PR DESCRIPTION
**Pull request by MattJLeach**
- Updated slide details for April 2019
- Removed background color on food-and-drink slide which caused an error
- changed a couple of size attributed to an object instead of a string

### CODE REVIEW

**Comment by admataz** [comment]
thanks @MattJLeach  - all looks good!

**Comment by MattJLeach** [comment]
@admataz - Do you have any preference / suggestions how you want it implemented?

**Comment by admataz** [comment]
@MattJLeach - it should be enough just be able to include one of the three slide graphics from that issue and add them into the MC slide deck like I did for Nexmo a few months ago (see: https://github.com/lnug/slides/blob/january-2019/presentation/index.js#L225)

**Comment by MattJLeach** [comment]
@admataz - I've added a slide for Pusher with the details of what they offer (I will also mention and talk a bit about what they offer as I am currently using their ChatKit on a project of mine).

Also added a small bit of text on the jobs slide to mention the new jobs table.

Let me know if this is all OK with you

**Comment by admataz** [comment]
that's great - thanks @MattJLeach ! see you later

**Pull request merged**
